### ISSUE TITLE
You have a mistake in the root README.md in the name of the module

### ISSUE THREAD

**Issue by QuestionAndAnswer** [gromnitsky/cidr.rb#1]

**Comment by gromnitsky** [comment]
hm, everything seems fine to me.
which line in README.md are you referring to exactly?

**Comment by QuestionAndAnswer** [comment]
I think, you just missed typo.

![image](https://cloud.githubusercontent.com/assets/6842709/23587856/4c087e6e-01c5-11e7-923a-b1c1c09b95d3.png)

**Comment by gromnitsky** [comment]
Fixed. Thanks!
